services:
  compilacion-go:
    build: .
    ports: 
      - "8080:8080"
      #nuestro servidor esta escuchando en el puerto 8080 segun el main.go
    depends_on:
      - database
  database:
    image: postgres:18
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - postgres_data:/var/lib/postgresql/data
    #puerto estandar de portgres
volumes:
postgres_data:
